version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:8.11.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test

workflows:
  sample:
    jobs:
      - build-and-test